[project]
name = "authForge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bharath Vishnu B", email = "bharathvb1204@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "pyyaml>=6.0.3",
    "rich>=15.0.0",
    "typer>=0.26.8",
]

[project.scripts]
authForge = "authForge:main"

[build-system]
requires = ["uv_build>=0.11.28,<0.12.0"]
build-backend = "uv_build"
